version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  app-node:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    container_name: app-node
    ports:
      - "6000:6000"
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/root/.ssh
    depends_on:
      - "dynamodb-local"
    links:
      - "dynamodb-local"
    command:
      sleep infinity